Dp custom order
slate-studio/dyno pull request #16
Opened 2018-04-01 19:46 UTC by DenisPopov15

2018-04-09 07:05 UTC, alexkravets requested changes

2018-04-09 07:05 UTC, alexkravets commented on lib/api/actions.js
> +    this.sortBy   = options.sortBy   || { position: 1, createdAt: -1 }
Doesn't look to be the right approach, as requires extra index to be created. I'm thinking about a way to generalize the approach and store position (probably not a good name cause of the context) for all docs based on `createdAt` with an option to update position.

2018-04-09 07:05 UTC, alexkravets commented on lib/db/mongodb/index.js
> +    if (options.customOrder) {
This should not be a schema option, should be removed. If plugin is used by some models, should be defined in a model not on a general level.

2018-04-09 07:05 UTC, alexkravets commented on lib/db/mongodb/plugins/customOrder.js
> +'use strict'
The problem with ordering is that we need a general approach of doing this. Creating indexes for many fields is not a good option as there is a limit on index name size. We had an issue with: staff profile: first name, last name, email — index is too long. Also if we generalize the ordering approach, we don't need to create custom indexes.

2018-04-09 08:31 UTC, alexkravets commented on lib/db/mongodb/plugins/customOrder.js
> +
`orderable`

2018-04-09 13:32 UTC, alexkravets commented on lib/db/mongodb/plugins/orderable.js
> +    this.constructor.find({}).sort(sortBy).limit(1)
Are you sure index is used in this case, do we need to add `_delete: true` or it's added automatically?

2018-04-09 13:34 UTC, alexkravets requested changes
Add tests, make sure created index is used.

2018-04-10 02:19 UTC, DenisPopov15 commented on lib/db/mongodb/plugins/orderable.js
> +    this.constructor.find({}).sort(sortBy).limit(1)
@alexkravets yes, seems so - here logs from this pre save hook : http://files.slatestudio.com/ql2W (deleted added automatic to query, index is used)

2018-04-10 03:13 UTC, DenisPopov15 commented
@alexkravets PR updated

2018-04-10 04:12 UTC, merged